name: main

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  main:
    uses: Tyrrrz/.github/.github/workflows/NuGet-WindowsOnly.yml@master
    with:
      publish-on-failed-tests: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}